export const BIBLE_BOOKS = [
  { name: 'Genesis', abbr: 'Gen', tagalog: 'Genesis', chapters: 50, testament: 'Old' },
  { name: 'Exodus', abbr: 'Exod', tagalog: 'Exodo', chapters: 40, testament: 'Old' },
  { name: 'Leviticus', abbr: 'Lev', tagalog: 'Levitico', chapters: 27, testament: 'Old' },
  { name: 'Numbers', abbr: 'Num', tagalog: 'Mga Bilang', chapters: 36, testament: 'Old' },
  { name: 'Deuteronomy', abbr: 'Deut', tagalog: 'Deuteronomio', chapters: 34, testament: 'Old' },
  { name: 'Joshua', abbr: 'Josh', tagalog: 'Josue', chapters: 24, testament: 'Old' },
  { name: 'Judges', abbr: 'Judg', tagalog: 'Mga Hukom', chapters: 21, testament: 'Old' },
  { name: 'Ruth', abbr: 'Ruth', tagalog: 'Ruth', chapters: 4, testament: 'Old' },
  { name: '1 Samuel', abbr: '1Sam', tagalog: '1 Samuel', chapters: 31, testament: 'Old' },
  { name: '2 Samuel', abbr: '2Sam', tagalog: '2 Samuel', chapters: 24, testament: 'Old' },
  { name: '1 Kings', abbr: '1Kgs', tagalog: '1 Mga Hari', chapters: 22, testament: 'Old' },
  { name: '2 Kings', abbr: '2Kgs', tagalog: '2 Mga Hari', chapters: 25, testament: 'Old' },
  { name: '1 Chronicles', abbr: '1Chr', tagalog: '1 Cronica', chapters: 29, testament: 'Old' },
  { name: '2 Chronicles', abbr: '2Chr', tagalog: '2 Cronica', chapters: 36, testament: 'Old' },
  { name: 'Ezra', abbr: 'Ezra', tagalog: 'Ezra', chapters: 10, testament: 'Old' },
  { name: 'Nehemiah', abbr: 'Neh', tagalog: 'Nehemias', chapters: 13, testament: 'Old' },
  { name: 'Esther', abbr: 'Esth', tagalog: 'Esther', chapters: 10, testament: 'Old' },
  { name: 'Job', abbr: 'Job', tagalog: 'Job', chapters: 42, testament: 'Old' },
  { name: 'Psalms', abbr: 'Ps', tagalog: 'Mga Awit', chapters: 150, testament: 'Old' },
  { name: 'Proverbs', abbr: 'Prov', tagalog: 'Mga Kawikaan', chapters: 31, testament: 'Old' },
  { name: 'Ecclesiastes', abbr: 'Eccl', tagalog: 'Eclesiastes', chapters: 12, testament: 'Old' },
  { name: 'Song of Solomon', abbr: 'Song', tagalog: 'Awit ni Solomon', chapters: 8, testament: 'Old' },
  { name: 'Isaiah', abbr: 'Isa', tagalog: 'Isaias', chapters: 66, testament: 'Old' },
  { name: 'Jeremiah', abbr: 'Jer', tagalog: 'Jeremias', chapters: 52, testament: 'Old' },
  { name: 'Lamentations', abbr: 'Lam', tagalog: 'Mga Panaghoy', chapters: 5, testament: 'Old' },
  { name: 'Ezekiel', abbr: 'Ezek', tagalog: 'Ezekiel', chapters: 48, testament: 'Old' },
  { name: 'Daniel', abbr: 'Dan', tagalog: 'Daniel', chapters: 12, testament: 'Old' },
  { name: 'Hosea', abbr: 'Hos', tagalog: 'Oseas', chapters: 14, testament: 'Old' },
  { name: 'Joel', abbr: 'Joel', tagalog: 'Joel', chapters: 3, testament: 'Old' },
  { name: 'Amos', abbr: 'Amos', tagalog: 'Amos', chapters: 9, testament: 'Old' },
  { name: 'Obadiah', abbr: 'Obad', tagalog: 'Abdias', chapters: 1, testament: 'Old' },
  { name: 'Jonah', abbr: 'Jonah', tagalog: 'Jonas', chapters: 4, testament: 'Old' },
  { name: 'Micah', abbr: 'Mic', tagalog: 'Miqueas', chapters: 7, testament: 'Old' },
  { name: 'Nahum', abbr: 'Nah', tagalog: 'Nahum', chapters: 3, testament: 'Old' },
  { name: 'Habakkuk', abbr: 'Hab', tagalog: 'Habacuc', chapters: 3, testament: 'Old' },
  { name: 'Zephaniah', abbr: 'Zeph', tagalog: 'Sofonias', chapters: 3, testament: 'Old' },
  { name: 'Haggai', abbr: 'Hag', tagalog: 'Hageo', chapters: 2, testament: 'Old' },
  { name: 'Zechariah', abbr: 'Zech', tagalog: 'Zacarias', chapters: 14, testament: 'Old' },
  { name: 'Malachi', abbr: 'Mal', tagalog: 'Malaquias', chapters: 4, testament: 'Old' },
  { name: 'Matthew', abbr: 'Matt', tagalog: 'Mateo', chapters: 28, testament: 'New' },
  { name: 'Mark', abbr: 'Mark', tagalog: 'Marcos', chapters: 16, testament: 'New' },
  { name: 'Luke', abbr: 'Luke', tagalog: 'Lucas', chapters: 24, testament: 'New' },
  { name: 'John', abbr: 'John', tagalog: 'Juan', chapters: 21, testament: 'New' },
  { name: 'Acts', abbr: 'Acts', tagalog: 'Mga Gawa', chapters: 28, testament: 'New' },
  { name: 'Romans', abbr: 'Rom', tagalog: 'Mga Taga-Roma', chapters: 16, testament: 'New' },
  { name: '1 Corinthians', abbr: '1Cor', tagalog: '1 Mga Taga-Corinto', chapters: 16, testament: 'New' },
  { name: '2 Corinthians', abbr: '2Cor', tagalog: '2 Mga Taga-Corinto', chapters: 13, testament: 'New' },
  { name: 'Galatians', abbr: 'Gal', tagalog: 'Mga Taga-Galacia', chapters: 6, testament: 'New' },
  { name: 'Ephesians', abbr: 'Eph', tagalog: 'Mga Taga-Efeso', chapters: 6, testament: 'New' },
  { name: 'Philippians', abbr: 'Phil', tagalog: 'Mga Taga-Filipos', chapters: 4, testament: 'New' },
  { name: 'Colossians', abbr: 'Col', tagalog: 'Mga Taga-Colosas', chapters: 4, testament: 'New' },
  { name: '1 Thessalonians', abbr: '1Thess', tagalog: '1 Mga Taga-Tesalonica', chapters: 5, testament: 'New' },
  { name: '2 Thessalonians', abbr: '2Thess', tagalog: '2 Mga Taga-Tesalonica', chapters: 3, testament: 'New' },
  { name: '1 Timothy', abbr: '1Tim', tagalog: '1 Timoteo', chapters: 6, testament: 'New' },
  { name: '2 Timothy', abbr: '2Tim', tagalog: '2 Timoteo', chapters: 4, testament: 'New' },
  { name: 'Titus', abbr: 'Titus', tagalog: 'Tito', chapters: 3, testament: 'New' },
  { name: 'Philemon', abbr: 'Phlm', tagalog: 'Filemon', chapters: 1, testament: 'New' },
  { name: 'Hebrews', abbr: 'Heb', tagalog: 'Mga Hebreo', chapters: 13, testament: 'New' },
  { name: 'James', abbr: 'Jas', tagalog: 'Santiago', chapters: 5, testament: 'New' },
  { name: '1 Peter', abbr: '1Pet', tagalog: '1 Pedro', chapters: 5, testament: 'New' },
  { name: '2 Peter', abbr: '2Pet', tagalog: '2 Pedro', chapters: 3, testament: 'New' },
  { name: '1 John', abbr: '1John', tagalog: '1 Juan', chapters: 5, testament: 'New' },
  { name: '2 John', abbr: '2John', tagalog: '2 Juan', chapters: 1, testament: 'New' },
  { name: '3 John', abbr: '3John', tagalog: '3 Juan', chapters: 1, testament: 'New' },
  { name: 'Jude', abbr: 'Jude', tagalog: 'Judas', chapters: 1, testament: 'New' },
  { name: 'Revelation', abbr: 'Rev', tagalog: 'Pahayag', chapters: 22, testament: 'New' },
];

export type BibleVersion = 'kjv' | 'web' | 'bsb' | 'asv' | 'bbe' | 'clementine' | 'darby' | 'ylt' | 'tagalog';

export const BIBLE_VERSIONS = [
  { value: 'kjv', label: 'King James Version (KJV)' },
  { value: 'web', label: 'World English Bible (WEB)' },
  { value: 'bsb', label: 'Berean Study Bible (BSB)' },
  { value: 'asv', label: 'American Standard Version (ASV)' },
  { value: 'bbe', label: 'Bible in Basic English (BBE)' },
  { value: 'clementine', label: 'Clementine Latin Vulgate' },
  { value: 'darby', label: 'Darby Translation' },
  { value: 'ylt', label: "Young's Literal Translation" },
  { value: 'tagalog', label: 'Ang Biblia (Tagalog)' },
];

export function getBookDisplayName(bookName: string, version: string): string {
  const book = BIBLE_BOOKS.find(b => b.name === bookName);
  if (!book) return bookName;

  const isTagalog = version?.toLowerCase() === 'tagalog';
  return isTagalog ? book.tagalog : book.name;
}
